allowBuilds:
  bigint-buffer: true
  bufferutil: true
  esbuild: true
  keccak: true
  secp256k1: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@solana/accounts@8.1.0'
  - '@solana/addresses@8.1.0'
  - '@solana/assertions@8.1.0'
  - '@solana/codecs-core@8.1.0'
  - '@solana/codecs-data-structures@8.1.0'
  - '@solana/codecs-numbers@8.1.0'
  - '@solana/codecs-strings@8.1.0'
  - '@solana/codecs@8.1.0'
  - '@solana/errors@8.1.0'
  - '@solana/fast-stable-stringify@8.1.0'
  - '@solana/fixed-points@8.1.0'
  - '@solana/functional@8.1.0'
  - '@solana/instruction-plans@8.1.0'
  - '@solana/instructions@8.1.0'
  - '@solana/keys@8.1.0'
  - '@solana/kit@8.1.0'
  - '@solana/nominal-types@8.1.0'
  - '@solana/offchain-messages@8.1.0'
  - '@solana/options@8.1.0'
  - '@solana/plugin-core@8.1.0'
  - '@solana/plugin-interfaces@8.1.0'
  - '@solana/program-client-core@8.1.0'
  - '@solana/programs@8.1.0'
  - '@solana/promises@8.1.0'
  - '@solana/rpc-api@8.1.0'
  - '@solana/rpc-parsed-types@8.1.0'
  - '@solana/rpc-spec-types@8.1.0'
  - '@solana/rpc-spec@8.1.0'
  - '@solana/rpc-subscriptions-api@8.1.0'
  - '@solana/rpc-subscriptions-channel-websocket@8.1.0'
  - '@solana/rpc-subscriptions-spec@8.1.0'
  - '@solana/rpc-subscriptions@8.1.0'
  - '@solana/rpc-transformers@8.1.0'
  - '@solana/rpc-transport-http@8.1.0'
  - '@solana/rpc-types@8.1.0'
  - '@solana/rpc@8.1.0'
  - '@solana/signers@8.1.0'
  - '@solana/subscribable@8.1.0'
  - '@solana/sysvars@8.1.0'
  - '@solana/transaction-confirmation@8.1.0'
  - '@solana/transaction-introspection@8.1.0'
  - '@solana/transaction-messages@8.1.0'
  - '@solana/transactions@8.1.0'
